ARG DOCKERSRC=frommakefile
#
FROM ${DOCKERSRC}
#
ARG PUID=1000
ARG PGID=1000
ENV CNTUSER=alpine \
    CNTPASS=insecurebydefault \
    CNTHOME=/home/alpine
#
RUN set -xe \
#   && echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
#   && echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
    && apk add --no-cache --purge -uU \
        curl \
        git \
        openssl \
        openssh \
	autossh \
	sshfs \
        rsync \
    && rm -rf /var/cache/apk/* /tmp/*
#
COPY root/ /
#
VOLUME /home/${CNTUSER}/ /etc/ssh/
#
EXPOSE 64822
#
ENTRYPOINT ["/init"]
# ENTRYPOINT ["/bin/bash"]
