#!/usr/bin/with-contenv bash

# make sure configs exist
[[ -f /etc/ssh/ssh_config  ]] || cp /defaults/ssh_config /etc/ssh/;
[[ -f /etc/ssh/sshd_config  ]] || cp /defaults/sshd_config /etc/ssh/;

# generate host keys, bind mount /etc/ssh to somewhere local if you need to preserve them
[[ -f /etc/ssh/ssh_host_rsa_key  ]] || (
    echo "Generating host keys.";
    ssh-keygen -t rsa -b 1024 -N "" -f /etc/ssh/ssh_host_rsa_key;
    ssh-keygen -t dsa -b 1024 -N "" -f /etc/ssh/ssh_host_dsa_key;
    ssh-keygen -t ecdsa -b 521 -N "" -f /etc/ssh/ssh_host_ecdsa_key;
    ssh-keygen -t ed25519 -b 512 -N "" -f /etc/ssh/ssh_host_ed25519_key;
)

# set root password if required
if [ -n "${ROOTPASS}" ];
then
    echo "Updating root password";
    echo  "root:${ROOTPASS}" | chpasswd;
fi;

# provide CNTPASS as well, the default is insecurebydefault
if [ -n "${CNTUSER}" ];
then
    echo "Adding user/group.";
    CNTHOME="/home/${CNTUSER}";
    addgroup -g "${PGID}" -S "${CNTUSER}";
    adduser -u "${PUID}" -G "${CNTUSER}" -h "${CNTHOME}" -D "${CNTUSER}" -s /bin/bash;
    echo  "${CNTUSER}:${CNTPASS}" | chpasswd;
# generate user keys
    [[ -f /home/${CNTUSER}/.ssh/id_rsa  ]] || (
        echo "Generating user keys.";
        s6-setuidgid ${CNTUSER} mkdir -p /home/${CNTUSER}/.ssh;
        s6-setuidgid ${CNTUSER} ssh-keygen -t rsa -b 1024 -N "" -f /home/${CNTUSER}/.ssh/id_rsa;
    )
fi;

